### ISSUE TITLE
國戰出雙勢力武將啦

### ISSUE THREAD

**Issue by ileadu** [yuzhicong/LTKHeroMaker#1]
如題
弄個可以生雙勢力武將的吧

**Comment by yuzhicong** [comment]
暂时没出实体卡牌，也没有模板素材，等后续有相关资源，会考虑添加国战双势力武将的制作



在 2021-07-18 03:50:12，"ileadu" ***@***.***> 写道：

如題
弄個可以生雙勢力武將的吧

**Comment by ileadu** [comment]
今天開賣了不臣篇上
那個字體大小 可以再多一點嗎
有些字蠻多 但是我又不希望字變太小
希望字型大小的調整可以更多刻度可以修改

**Comment by yuzhicong** [comment]
国战双势力 已经支持
